---
- hosts: all
  become: yes
  become_method: sudo 
  tasks:
     - name: copy artifacts from server to all appservers
     file: src=/home/jenkins/slave-repo/workspace/s3-deploy-tomcat/gameoflife.war dest=/usr/local/tomcat/webapps/
