# copywarfile.yml
---
- hosts: all 
  become: true
  tasks: 
    - name: copy jar/war onto tomcat servers
      copy:
          src: /etc/ansible/playbooks/gameoflife-web/target/gameoflife.war
          dest: /usr/share/tomcat/webapps
