---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible

  tasks:
    - name: add several users
    user:
      name: "{{ item }}"
      state: present
      groups: "classgroup"
    with_items:
      - shiva
      - surya
      - kiran

