---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: add several users
      user:
        name: "{{ item }}"
        state: present
        groups: "ansadm"
      with_items:
        - shiva
        - surya
        - kiran
